# Generated by Django 4.2.27 on 2026-01-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_add_plan_cycle'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='plan_cycle',
            field=models.ForeignKey(blank=True, help_text='Optional link to PlanCycle for period-based tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='plans.plancycle'),
        ),
    ]
