# Generated by Django 4.2.27 on 2026-01-29 03:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0003_add_exercise_fields_and_training_entry'),
        ('clients', '0002_add_user_field'),
        ('plans', '0008_revert_meal_unique_constraint'),
        ('tracking', '0002_add_plan_cycle_to_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adherence_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calories_estimate_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_estimate_g', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs_estimate_g', models.PositiveIntegerField(blank=True, null=True)),
                ('fats_estimate_g', models.PositiveIntegerField(blank=True, null=True)),
                ('hunger_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cravings_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('digestion_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='clients.client')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_logs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('plan_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_logs', to='plans.plancycle')),
            ],
            options={
                'db_table': 'diet_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('execution_status', models.CharField(choices=[('not_done', 'Not Done'), ('partial', 'Partial'), ('done', 'Done'), ('replaced', 'Replaced'), ('injury_stop', 'Injury Stop'), ('sick', 'Sick')], default='not_done', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Rate of Perceived Exertion 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='clients.client')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('executed_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_logs', to='catalogs.exercise')),
                ('plan_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='plans.plancycle')),
                ('suggested_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_logs', to='catalogs.exercise')),
            ],
            options={
                'db_table': 'training_logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'date'], name='training_lo_client__bcfb77_idx'), models.Index(fields=['plan_cycle', 'date'], name='training_lo_plan_cy_5d8d23_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='traininglog',
            constraint=models.UniqueConstraint(fields=('client', 'date'), name='training_logs_client_date_unique'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['client', 'date'], name='diet_logs_client__6e8def_idx'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['plan_cycle', 'date'], name='diet_logs_plan_cy_47f2b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='dietlog',
            constraint=models.UniqueConstraint(fields=('client', 'date'), name='diet_logs_client_date_unique'),
        ),
    ]
