# Generated by Django 4.2.27 on 2026-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_training_group_and_meal_foods'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailydietrecommendation',
            new_name='daily_diet__client__a8a165_idx',
            old_name='daily_diet__client__idx',
        ),
        migrations.RenameIndex(
            model_name='dailytrainingrecommendation',
            new_name='daily_train_client__33d049_idx',
            old_name='daily_train_client__idx',
        ),
        migrations.AddIndex(
            model_name='dailyexerciserecommendation',
            index=models.Index(fields=['client', 'date'], name='daily_exerc_client__19dc40_idx'),
        ),
    ]
