# Generated by Django 4.2.27 on 2026-01-28 00:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_add_user_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='Scheduled date and time for the appointment')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes (minimum 15)', validators=[django.core.validators.MinValueValidator(15)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the appointment')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this consultation (required)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='MXN', help_text='Currency code (e.g., MXN, USD)', max_length=3)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], help_text='Payment method used (if paid)', max_length=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was recorded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['client', 'scheduled_at'], name='appointment_client__ccc76a_idx'), models.Index(fields=['coach', 'scheduled_at'], name='appointment_coach_i_92127d_idx'), models.Index(fields=['status', 'scheduled_at'], name='appointment_status_e303fa_idx')],
            },
        ),
    ]
