# Generated by Django 5.0.2 on 2025-08-16 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('cut', 'Cut (Weight Loss)'), ('bulk', 'Bulk (Muscle Gain)'), ('maintain', 'Maintain')], max_length=10)),
                ('daily_calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(5000)])),
                ('protein_pct', models.DecimalField(decimal_places=1, help_text='Protein percentage of total calories', max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('carbs_pct', models.DecimalField(decimal_places=1, help_text='Carbohydrates percentage of total calories', max_digits=4, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(70)])),
                ('fat_pct', models.DecimalField(decimal_places=1, help_text='Fat percentage of total calories', max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diet_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reps_or_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('set_type', models.CharField(choices=[('reps', 'Repetitions'), ('time', 'Time (seconds)'), ('duration', 'Duration (minutes)')], default='reps', max_length=10)),
                ('rest_seconds', models.PositiveIntegerField(default=60, help_text='Rest time in seconds', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'exercise_sets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, help_text='Quantity in grams or milliliters', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'meal_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('diet', 'Diet Plan'), ('workout', 'Workout Plan')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'workout_days',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Muscle Growth'), ('endurance', 'Endurance'), ('weight_loss', 'Weight Loss'), ('general', 'General Fitness')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
