# Generated by Django 5.0.2 on 2025-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
