# Generated by Django 4.2.27 on 2026-01-27 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_user_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0003_dietplan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('goal', models.CharField(blank=True, choices=[('fat_loss', 'Fat Loss'), ('recomp', 'Recomposition'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the coach')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cycles', to='clients.client')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_plan_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan_cycles',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='planassignment',
            name='plan_cycle',
            field=models.ForeignKey(blank=True, help_text='Optional link to PlanCycle for period-based tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='plans.plancycle'),
        ),
        migrations.AddIndex(
            model_name='plancycle',
            index=models.Index(fields=['client', 'status'], name='plan_cycles_client__5c8c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='plancycle',
            index=models.Index(fields=['client', 'start_date', 'end_date'], name='plan_cycles_client__775d21_idx'),
        ),
    ]
