# Generated by Django 4.2.27 on 2026-01-28 02:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_add_exercise_fields_and_training_entry'),
        ('plans', '0004_add_plan_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date/session for this training entry')),
                ('series', models.PositiveIntegerField(help_text='Number of sets', validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.CharField(help_text="Repetitions (e.g., '8-12' or '10')", max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (optional, for bodyweight exercises leave blank)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_seconds', models.PositiveIntegerField(blank=True, help_text='Rest time in seconds (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this training entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(help_text='Exercise for this training entry', on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='catalogs.exercise')),
                ('workout_plan', models.ForeignKey(help_text='Workout plan this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_entries', to='plans.workoutplan')),
            ],
            options={
                'db_table': 'training_entries',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['workout_plan', 'date'], name='training_en_workout_77dd41_idx'), models.Index(fields=['exercise'], name='training_en_exercis_faa315_idx')],
            },
        ),
    ]
