# Generated by Django 4.2.27 on 2026-01-28 02:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_add_exercise_fields_and_training_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['order', 'meal_type']},
        ),
        migrations.AddField(
            model_name='dietplan',
            name='plan_cycle',
            field=models.OneToOneField(blank=True, help_text='Link to PlanCycle (one diet plan per cycle)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan', to='plans.plancycle'),
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, help_text="Free-text meal description (e.g., 'pan tostado con aguacate...')"),
        ),
        migrations.AddField(
            model_name='plancycle',
            name='plan_pdf',
            field=models.FileField(blank=True, help_text='Generated PDF of the complete plan', null=True, upload_to='plan_pdfs/'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_cycle',
            field=models.OneToOneField(blank=True, help_text='Link to PlanCycle (one workout plan per cycle)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='plans.plancycle'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='carbs_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Carbohydrates percentage of total calories', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_calories',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='fat_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fat percentage of total calories', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(blank=True, choices=[('cut', 'Cut (Weight Loss)'), ('bulk', 'Bulk (Muscle Gain)'), ('maintain', 'Maintain')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='protein_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Protein percentage of total calories', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Desayuno'), ('pre_workout', 'Pre-entreno'), ('post_workout', 'Post-entreno'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('hypertrophy', 'Muscle Growth'), ('endurance', 'Endurance'), ('weight_loss', 'Weight Loss'), ('general', 'General Fitness')], max_length=15),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
