# Generated by Django 4.2.27 on 2026-01-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_link_plans_to_cycle_and_add_pdf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('diet_plan', 'meal_type')},
        ),
    ]
