# Generated by Django 4.2.27 on 2026-01-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_change_meal_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('diet_plan', 'meal_type', 'order')},
        ),
    ]
