# Generated by Django 4.2.27 on 2026-03-07 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours_sleep', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motivation_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('soreness_legs', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('soreness_arms', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('soreness_core', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('soreness_shoulders', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('joint_pain', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_notes', models.TextField(blank=True)),
                ('did_gym_today', models.BooleanField(default=False)),
                ('did_gym_yesterday', models.BooleanField(default=False)),
                ('gym_focus', models.CharField(blank=True, max_length=100)),
                ('wants_intensity', models.CharField(blank=True, help_text='e.g. low, moderate, high', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_daily_checkins',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('recommendation_type', models.CharField(choices=[('recovery', 'Recovery'), ('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense'), ('mixed', 'Mixed')], default='moderate', max_length=20)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('coach_message', models.TextField(blank=True)),
                ('rule_based_payload', models.JSONField(blank=True, default=dict)),
                ('llm_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_recommendations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('plyometrics', 'Plyometrics'), ('core', 'Core'), ('recovery', 'Recovery'), ('mixed', 'Mixed'), ('other', 'Other')], default='mixed', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('max', 'Max')], default='moderate', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True)),
                ('stresses_legs', models.BooleanField(default=False)),
                ('stresses_upper_body', models.BooleanField(default=False)),
                ('stresses_core', models.BooleanField(default=False)),
                ('explosive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'training_videos',
                'ordering': ['program', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('completed', models.BooleanField(default=True)),
                ('paused', models.BooleanField(default=False)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Rate of Perceived Exertion 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('breathing', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sweat_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('performance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('felt_strong', models.BooleanField(blank=True, null=True)),
                ('felt_drained', models.BooleanField(blank=True, null=True)),
                ('recovery_fast', models.BooleanField(blank=True, null=True)),
                ('pain_during_workout', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_notes', models.TextField(blank=True)),
                ('body_feedback', models.TextField(blank=True)),
                ('emotional_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_workout_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_logs', to='training.trainingvideo')),
            ],
            options={
                'db_table': 'training_workout_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['is_active', 'category'], name='training_vi_is_acti_97b054_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['is_active', 'difficulty'], name='training_vi_is_acti_0e79a9_idx'),
        ),
        migrations.AddField(
            model_name='trainingrecommendation',
            name='recommended_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='training.trainingvideo'),
        ),
        migrations.AddField(
            model_name='trainingrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', 'date'], name='training_wo_user_id_d5c185_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecommendation',
            index=models.Index(fields=['user', 'date'], name='training_re_user_id_1e9c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='training_recommendation_user_date_unique'),
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['user', 'date'], name='training_da_user_id_f907ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='training_daily_checkin_user_date_unique'),
        ),
    ]
