# Generated by Django 4.2.27 on 2026-03-07 23:02

import django.core.validators
from django.db import migrations, models


def _drop_check_constraints_for_boolean_conversion(apps, schema_editor):
    """Drop CHECK constraints on columns we're converting to boolean (e.g. joint_pain >= 0)."""
    # Drop all check constraints on these tables so ALTER TYPE doesn't hit "boolean >= integer"
    schema_editor.execute(
        """
        DO $inner$
        DECLARE r RECORD;
        BEGIN
          FOR r IN
            SELECT c.conname FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            WHERE t.relname = 'training_daily_checkins' AND c.contype = 'c'
          LOOP
            EXECUTE format('ALTER TABLE training_daily_checkins DROP CONSTRAINT %%I', r.conname);
          END LOOP;
        END $inner$;
        """
    )
    schema_editor.execute(
        """
        DO $inner$
        DECLARE r RECORD;
        BEGIN
          FOR r IN
            SELECT c.conname FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            WHERE t.relname = 'training_workout_logs' AND c.contype = 'c'
          LOOP
            EXECUTE format('ALTER TABLE training_workout_logs DROP CONSTRAINT %%I', r.conname);
          END LOOP;
        END $inner$;
        """
    )


def _alter_joint_pain_to_boolean(apps, schema_editor):
    """Convert joint_pain smallint -> boolean (PostgreSQL cannot cast directly)."""
    schema_editor.execute(
        'ALTER TABLE training_daily_checkins '
        'ALTER COLUMN joint_pain TYPE boolean USING (COALESCE(joint_pain, 0)::int <> 0)'
    )


def _alter_wants_intensity_to_boolean(apps, schema_editor):
    """Convert wants_intensity varchar -> boolean."""
    schema_editor.execute(
        "ALTER TABLE training_daily_checkins "
        "ALTER COLUMN wants_intensity TYPE boolean USING "
        "(LOWER(TRIM(COALESCE(wants_intensity, ''))) NOT IN ('false', 'no', '0'))"
    )


def _alter_pain_during_workout_to_boolean(apps, schema_editor):
    """Convert pain_during_workout smallint -> boolean (WorkoutLog)."""
    schema_editor.execute(
        'ALTER TABLE training_workout_logs '
        'ALTER COLUMN pain_during_workout TYPE boolean USING (COALESCE(pain_during_workout, 0)::int <> 0)'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycheckin',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trainingrecommendation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='dailycheckin',
            name='training_daily_checkin_user_date_unique',
        ),
        migrations.RemoveConstraint(
            model_name='trainingrecommendation',
            name='training_recommendation_user_date_unique',
        ),
        migrations.RemoveIndex(
            model_name='trainingvideo',
            name='training_vi_is_acti_97b054_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingvideo',
            name='training_vi_is_acti_0e79a9_idx',
        ),
        # smallint/varchar -> boolean: drop CHECK constraints first (they use integer comparison),
        # then explicit USING. SeparateDatabaseAndState so Django does not run a second ALTER.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_drop_check_constraints_for_boolean_conversion, migrations.RunPython.noop),
                migrations.RunPython(_alter_joint_pain_to_boolean, migrations.RunPython.noop),
                migrations.RunPython(_alter_wants_intensity_to_boolean, migrations.RunPython.noop),
                migrations.RunPython(_alter_pain_during_workout_to_boolean, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='dailycheckin',
                    name='joint_pain',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='dailycheckin',
                    name='wants_intensity',
                    field=models.BooleanField(default=True),
                ),
                migrations.AlterField(
                    model_name='workoutlog',
                    name='pain_during_workout',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='soreness_arms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='soreness_core',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='soreness_legs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='soreness_shoulders',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='trainingrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('recovery', 'Recovery'), ('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense'), ('max', 'Max')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('recovery', 'Recovery'), ('plyometrics', 'Plyometrics'), ('core', 'Core'), ('strength', 'Strength'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='difficulty',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('max', 'Max')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='program',
            field=models.CharField(blank=True, default='Insanity', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='stresses_core',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='stresses_legs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='breathing',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='performance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='training_daily_checkins_user_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='training_recommendations_user_date_unique'),
        ),
    ]
