# Generated by Django 4.2.27 on 2026-03-10 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_client_coach_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height_m',
            field=models.DecimalField(decimal_places=2, help_text='Height in meters (e.g. 1.85)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.5)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', help_text='Client level for AI routine suggestions', max_length=12),
        ),
    ]
