# Generated by Django 4.2.27 on 2026-01-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientSubscription',
        ),
    ]
