# Generated by Django 5.0.2 on 2025-08-16 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('core', 'Core'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='Optional video demonstration URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('serving_size', models.DecimalField(decimal_places=1, help_text='Serving size in grams or milliliters', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('kcal', models.DecimalField(decimal_places=1, help_text='Calories per serving', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=1, help_text='Protein in grams per serving', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_g', models.DecimalField(decimal_places=1, help_text='Carbohydrates in grams per serving', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g', models.DecimalField(decimal_places=1, help_text='Fat in grams per serving', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foods',
                'ordering': ['name'],
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
