# Generated by Django 4.2.27 on 2026-01-28 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='food',
            name='calories_kcal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calories per 100g (kcal)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='creatine_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Creatine in milligrams per 100g (optional)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='fats_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fats in grams per 100g', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fiber in grams per 100g (optional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='micronutrients_notes',
            field=models.TextField(blank=True, help_text='Notes about micronutrients'),
        ),
        migrations.AddField(
            model_name='food',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes, sources, remarks'),
        ),
        migrations.AddField(
            model_name='food',
            name='nutritional_group',
            field=models.CharField(blank=True, choices=[('cereales_tuberculos_derivados', 'Cereales, tubérculos y derivados.'), ('frutas_verduras', 'Frutas y verduras.'), ('leche_derivados', 'Leche y derivados.'), ('carnes_legumbres_huevos', 'Carnes, legumbres secas y huevos.'), ('azucares_mieles', 'Azúcares o mieles.'), ('aceites_grasas', 'Aceites o grasas.')], help_text='Nutritional group classification', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='origin_classification',
            field=models.CharField(blank=True, choices=[('vegetal', 'Vegetal'), ('animal', 'Animal'), ('mineral', 'Mineral')], help_text='Origin classification', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='water_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Water in grams per 100g (optional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Carbohydrates in grams per 100g', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fat in grams per serving (legacy - use fats_g per 100g)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calories per serving (legacy - use calories_kcal per 100g)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Food name (unique)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Protein in grams per 100g', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, default=100.0, help_text='Serving size in grams or milliliters', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='foods_name_01bd69_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['nutritional_group'], name='foods_nutriti_a7ea44_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['origin_classification'], name='foods_origin__e2c434_idx'),
        ),
    ]
