# Generated by Django 4.2.27 on 2026-01-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_add_food_nutrition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('mancuerna', 'Mancuerna'), ('barra', 'Barra'), ('maquina', 'Máquina'), ('peso_corporal', 'Peso Corporal'), ('banda', 'Banda de Resistencia'), ('cable', 'Cable'), ('kettlebell', 'Kettlebell'), ('otro', 'Otro')], help_text='Type of equipment required', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for the exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, help_text='Specific equipment name (legacy field, use equipment_type)', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(help_text='Exercise instructions (text or URL)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('core', 'Core'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], help_text='Muscle group', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='Exercise name (unique)', max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercises_name_26c749_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group'], name='exercises_muscle__f519d0_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['equipment_type'], name='exercises_equipme_53b2ae_idx'),
        ),
    ]
